[project]
name = "obesity"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "kaleido>=1.2.0",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "seaborn>=0.13.2",
]
